export const services = [
  {
    slug: "seo",
    title: "SEO & Organic Growth",
    shortTitle: "SEO",
    icon: "Search",
    description: "Dominate search rankings with data-driven SEO strategies tailored for your industry.",
    color: "#2563eb",
    features: ["Technical SEO Audits", "Content Strategy", "Link Building", "Local SEO"],
    stat: "450%",
    statLabel: "Average Organic Traffic Increase",
  },
  {
    slug: "ppc",
    title: "PPC & Paid Advertising",
    shortTitle: "PPC",
    icon: "Target",
    description: "High-ROI paid campaigns across Google, Meta, LinkedIn and more.",
    color: "#06b6d4",
    features: ["Google Ads", "Meta Advertising", "LinkedIn Ads", "Retargeting"],
    stat: "3.8x",
    statLabel: "Average ROAS",
  },
  {
    slug: "social-media",
    title: "Social Media Marketing",
    shortTitle: "Social Media",
    icon: "Share2",
    description: "Build an engaged community and drive conversions through strategic social presence.",
    color: "#8b5cf6",
    features: ["Content Creation", "Community Management", "Influencer Outreach", "Analytics"],
    stat: "280%",
    statLabel: "Engagement Rate Increase",
  },
  {
    slug: "content-marketing",
    title: "Content Marketing",
    shortTitle: "Content",
    icon: "FileText",
    description: "Compelling content that attracts, educates, and converts your ideal customers.",
    color: "#f59e0b",
    features: ["Blog Strategy", "Video Content", "Case Studies", "Whitepapers"],
    stat: "5x",
    statLabel: "Lead Generation Uplift",
  },
  {
    slug: "web-design",
    title: "Web Design & CRO",
    shortTitle: "Web Design",
    icon: "Monitor",
    description: "Conversion-optimised websites that turn visitors into loyal customers.",
    color: "#10b981",
    features: ["UX/UI Design", "A/B Testing", "Landing Pages", "Speed Optimization"],
    stat: "62%",
    statLabel: "Average Conversion Increase",
  },
  {
    slug: "email-marketing",
    title: "Email Marketing",
    shortTitle: "Email",
    icon: "Mail",
    description: "Automated email journeys that nurture leads and drive repeat revenue.",
    color: "#ef4444",
    features: ["Campaign Strategy", "Automation Flows", "Segmentation", "Deliverability"],
    stat: "42%",
    statLabel: "Average Open Rate",
  },
  {
    slug: "analytics",
    title: "Analytics & Reporting",
    shortTitle: "Analytics",
    icon: "BarChart2",
    description: "Crystal-clear reporting dashboards with actionable insights for growth decisions.",
    color: "#6366f1",
    features: ["GA4 Setup", "Custom Dashboards", "Attribution Modelling", "Monthly Reports"],
    stat: "100%",
    statLabel: "Data-Driven Decisions",
  },
];

export const industries = [
  {
    slug: "hospitality",
    title: "Hospitality & Hotels",
    icon: "Building2",
    description: "Digital marketing for hotels, resorts, and hospitality groups to increase direct bookings.",
    color: "#f59e0b",
  },
  {
    slug: "restaurants",
    title: "Restaurants & Food",
    icon: "UtensilsCrossed",
    description: "Drive footfall and online orders for restaurants, cafes, and food brands.",
    color: "#ef4444",
  },
  {
    slug: "ecommerce",
    title: "E-Commerce",
    icon: "ShoppingBag",
    description: "Scale your online store with performance marketing and conversion strategies.",
    color: "#10b981",
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    icon: "Briefcase",
    description: "Lead generation for law firms, accountants, and consultancies.",
    color: "#2563eb",
  },
  {
    slug: "healthcare",
    title: "Healthcare & Wellness",
    icon: "Heart",
    description: "Patient acquisition and brand awareness for clinics and wellness centres.",
    color: "#06b6d4",
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    icon: "Home",
    description: "Digital strategies for estate agents and property developers.",
    color: "#8b5cf6",
  },
  {
    slug: "technology",
    title: "Technology & SaaS",
    icon: "Cpu",
    description: "B2B and B2C marketing for tech companies and SaaS platforms.",
    color: "#6366f1",
  },
  {
    slug: "education",
    title: "Education & Training",
    icon: "GraduationCap",
    description: "Student acquisition and brand building for educational institutions.",
    color: "#f97316",
  },
];

export const testimonials = [
  {
    name: "James Harrington",
    role: "CEO, The Grand Mayfair Hotel",
    image: "/testimonials/james.jpg",
    content:
      "SparxGrowth transformed our digital presence completely. Our direct bookings increased by 340% in just 6 months. Absolutely phenomenal results.",
    rating: 5,
    result: "+340% Direct Bookings",
  },
  {
    name: "Sarah Chen",
    role: "Marketing Director, Luxe Eats Group",
    image: "/testimonials/sarah.jpg",
    content:
      "Their SEO strategy pushed us to #1 for all our target keywords. The team is incredibly knowledgeable and proactive. Couldn't recommend more.",
    rating: 5,
    result: "#1 Google Rankings",
  },
  {
    name: "Mohammed Al-Rashid",
    role: "Founder, TechLaunch UK",
    image: "/testimonials/mohammed.jpg",
    content:
      "ROI from their PPC campaigns is consistently above 5x. The reporting is transparent and the team genuinely cares about our business growth.",
    rating: 5,
    result: "5x ROAS Achieved",
  },
  {
    name: "Emma Williams",
    role: "Director, Bloom Wellness Clinics",
    image: "/testimonials/emma.jpg",
    content:
      "Within 3 months, our patient enquiries tripled. SparxGrowth truly understands the healthcare space and delivers exceptional results.",
    rating: 5,
    result: "3x Patient Enquiries",
  },
];

export const stats = [
  { value: 250, suffix: "+", label: "Brands Grown" },
  { value: 450, suffix: "%", label: "Avg Traffic Increase" },
  { value: 98, suffix: "%", label: "Client Retention Rate" },
  { value: 12, suffix: "M+", label: "Revenue Generated" },
];

export const blogPosts = [
  {
    slug: "seo-trends-2025",
    title: "10 SEO Trends That Will Define 2025",
    excerpt: "From AI-driven search to zero-click results, here's what your SEO strategy needs to prioritise this year.",
    category: "SEO",
    readTime: "7 min read",
    date: "March 20, 2026",
    image: "/blog/seo-trends.jpg",
  },
  {
    slug: "ppc-roi-hospitality",
    title: "How Hotels Can 4x Their PPC ROI",
    excerpt: "A deep dive into the paid advertising strategies that are driving exceptional results for luxury hotel brands.",
    category: "PPC",
    readTime: "5 min read",
    date: "March 15, 2026",
    image: "/blog/ppc-hospitality.jpg",
  },
  {
    slug: "social-media-restaurant",
    title: "Social Media Marketing for Restaurants in 2026",
    excerpt: "The complete playbook for building a loyal following and driving consistent footfall through social media.",
    category: "Social Media",
    readTime: "6 min read",
    date: "March 10, 2026",
    image: "/blog/social-restaurant.jpg",
  },
];
